use_frameworks!

target 'CountryAndCity_Example' do
  pod 'CountryAndCity', :path => '../'

  target 'CountryAndCity_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
